export default {
  CREATE_CHANNEL: 'trax/CREATE_CHANNEL',
  REMOVE_CHANNEL: 'trax/REMOVE_CHANNEL',
  ARCHIVE_CHANNEL: 'trax/ARCHIVE_CHANNEL',
  RESTORE_CHANNEL: 'trax/RESTORE_CHANNEL',
  TOGGLE_MUTE_CHANNEL: 'trax/TOGGLE_MUTE_CHANNEL',
  TOGGLE_SOLO_CHANNEL: 'trax/TOGGLE_SOLO_CHANNEL'
}
