export default {
  CREATE_CHANNEL: 'trax/CREATE_CHANNEL',
  REMOVE_CHANNEL: 'trax/REMOVE_CHANNEL',
  ARCHIVE_CHANNEL: 'trax/ARCHIVE_CHANNEL',
  RESTORE_CHANNEL: 'trax/RESTORE_CHANNEL',
  TOGGLE_MUTE_CHANNEL: 'trax/TOGGLE_MUTE_CHANNEL',
  TOGGLE_SOLO_CHANNEL: 'trax/TOGGLE_SOLO_CHANNEL',
  SET_BLIP_AT: 'trax/SET_BLIP_AT',
  TOGGLE_BLIP_AT: 'trax/TOGGLE_BLIP_AT'
}
