export default {
  CREATE_SONG_PLAYER: 'trax/song-player/CREATE_SONG_PLAYER',
  SET_START: 'trax/song-player/SET_START',
  SET_CURRENT_PLAYING_LINE: 'trax/song-player/SET_CURRENT_PLAYING_LINE',
  RESET_CURRENT_PLAYING_LINE: 'trax/song-player/RESET_CURRENT_PLAYING_LINE',
  INC_CURRENT_PLAYING_LINE: 'trax/song-player/INC_CURRENT_PLAYING_LINE',
}
